#!/usr/bin/env python
# -*- coding: UTF-8 -*-
__author__ = 'kevin'

from core.logger import logger
from core.base_controller import BaseHandler
from core.DB import DBSession
from models.movie import Movie

result_format = {
    'id':'',
    'nm':'',
    'sellPrice':'',
    'addr':'',
    'distance':'',
    'endorse':'',
    'allowRefund':'',
    'hallType':'',
    'snack':'',
    'vipDesc':'',
    "promotion":{
                    "cardPromotionTag":"开卡特惠，25元起开卡",
    },
    'showTimes':
}

result = {
        "cinemas":[
            {
                "addr":"市北区嘉善路72号甲大地影院（工商银行旁边下台阶即到）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":17103,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.108284,
                "lng":120.3615,
                "mark":0,
                "nm":"大地影院（人民路商业广场店）",
                "poiId":152316938,
                "price":33,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，25元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":1000,
                "sellPrice":"33",
                "shopId":79217325,
                "showTimes":"近期场次: 14:40 | 15:50 | 17:00",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"黄岛区王台镇环台北路82号328创意广场",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":16792,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"4K厅",
                        "url":""
                    }
                ],
                "lat":36.08266,
                "lng":120.006874,
                "mark":0,
                "nm":"西海岸电影城（王台店）",
                "poiId":150069070,
                "price":32.98,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，11.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":960.00006,
                "sellPrice":"32.98",
                "shopId":76985713,
                "showTimes":"近期场次: 14:30 | 15:40 | 17:00",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[
                        "4K厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"4K厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"市南区中山路97号（中山路派出所斜对面）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":1116,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"DTS:X 临境音厅",
                        "url":""
                    }
                ],
                "lat":36.0689,
                "lng":120.3187,
                "mark":0,
                "nm":"中国电影院",
                "poiId":1543526,
                "price":39,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，24.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"25",
                "score":944.44446,
                "sellPrice":"39",
                "shopId":1693924,
                "showTimes":"近期场次: 14:35 | 17:00 | 19:20",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[
                        "DTS:X 临境音厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"DTS:X 临境音厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区棘洪滩街道青大社区中心（南万小学对面）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":11535,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.320045,
                "lng":120.322586,
                "mark":0,
                "nm":"棘洪滩影城",
                "poiId":5653509,
                "price":33,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，11.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":931.5789,
                "sellPrice":"33",
                "shopId":19644320,
                "showTimes":"近期场次: 15:55 | 18:15 | 20:35",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"市北区黑龙江南路18号凯德MALL5楼",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":15908,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"IMAX厅",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"60帧厅",
                        "url":""
                    }
                ],
                "lat":36.114384,
                "lng":120.39599,
                "mark":0,
                "nm":"CGV影城（新都心IMAX店）",
                "poiId":92133467,
                "price":44,
                "promotion":{
                    "cardPromotionTag":"",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":925,
                "sellPrice":"44",
                "shopId":67314377,
                "showTimes":"近期场次: 15:30 | 16:40 | 17:55",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[
                        "IMAX厅",
                        "60帧厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"IMAX厅",
                            "url":""
                        },
                        {
                            "name":"60帧厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"崂山区海尔路83号金鼎广场7楼",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":16263,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"MX4D厅",
                        "url":""
                    }
                ],
                "lat":36.0933,
                "lng":120.46317,
                "mark":0,
                "nm":"利群华艺影院（金鼎广场4k巨幕MX4D店）",
                "poiId":118503086,
                "price":33,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，24.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":908.3333,
                "sellPrice":"33",
                "shopId":69454165,
                "showTimes":"近期场次: 14:40 | 15:40 | 17:05",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[
                        "MX4D厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"MX4D厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"即墨区即墨市鹤山路999号家佳源购物中心三层",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":7799,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.397686,
                "lng":120.41999,
                "mark":0,
                "nm":"大地影院（即墨家佳源店）",
                "poiId":4148359,
                "price":35,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，25元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":892.8572,
                "sellPrice":"35",
                "shopId":17721483,
                "showTimes":"近期场次: 14:20 | 16:40 | 17:40",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"即墨区即墨市鹤山路939号，利群购物中心7楼（小商品城对面）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":8093,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.398003,
                "lng":120.42765,
                "mark":0,
                "nm":"利群华艺影院（即墨激光巨幕店）",
                "poiId":4118586,
                "price":39,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，24.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":878.5714,
                "sellPrice":"39",
                "shopId":17902216,
                "showTimes":"近期场次: 15:20 | 16:40 | 17:40",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"即墨区即墨市即墨振华街100号（新华书店东50米）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":567,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.389435,
                "lng":120.45585,
                "mark":0,
                "nm":"新时代电影城",
                "poiId":1438384,
                "price":38,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，24.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"50",
                "score":877.7778,
                "sellPrice":"38",
                "shopId":11189640,
                "showTimes":"近期场次: 14:20 | 15:00 | 15:45",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"即墨区即墨市鹤山路599号（佳乐家3层）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":0,
                "distance":"",
                "follow":0,
                "id":1924,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.396877,
                "lng":120.45436,
                "mark":0,
                "nm":"艺佳圣帝亚电影城",
                "poiId":1554524,
                "price":38,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，11.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"60",
                "score":866.6667,
                "sellPrice":"38",
                "shopId":6157825,
                "showTimes":"近期场次: 16:20 | 18:40 | 19:40",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            }
        ],
        "ct_pois":[
            {
                "ct_poi":"936879945111165696_a17103_c0",
                "poiid":152316938
            },
            {
                "ct_poi":"936879945111165696_a16792_c1",
                "poiid":150069070
            },
            {
                "ct_poi":"936879945111165696_a1116_c2",
                "poiid":1543526
            },
            {
                "ct_poi":"936879945111165696_a11535_c3",
                "poiid":5653509
            },
            {
                "ct_poi":"936879945111165696_a15908_c4",
                "poiid":92133467
            },
            {
                "ct_poi":"936879945111165696_a16263_c5",
                "poiid":118503086
            },
            {
                "ct_poi":"936879945111165696_a7799_c6",
                "poiid":4148359
            },
            {
                "ct_poi":"936879945111165696_a8093_c7",
                "poiid":4118586
            },
            {
                "ct_poi":"936879945111165696_a567_c8",
                "poiid":1438384
            },
            {
                "ct_poi":"936879945111165696_a1924_c9",
                "poiid":1554524
            }
        ],
        "paging":{
            "hasMore":True,
            "limit":10,
            "offset":0,
            "total":75
        }
}

class AjaxMovieHandler(BaseHandler):
    def get(self, *args, **kwargs):
        logger.info('this is in MovieHandler')
        
        self.JsonResponse(result)