#!/usr/bin/env python
# -*- coding: UTF-8 -*-
__author__ = 'kevin'

from core.logger import logger
from core.base_controller import BaseHandler
from core.DB import DBSession
from models.cinema import Cinema
from geopy.distance import geodesic

cinemas = {
        "cinemas":[
            {
                "addr":"城阳区正阳中路与长城交叉口处东北侧",
                "cellShows":[

                ],
                "cityId":60,
                "dis":629.2487145661082,
                "distance":"0.6km",
                "follow":0,
                "id":16254,
                "labels":[
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.307068,
                "lng":120.403305,
                "mark":0,
                "nm":"东影时代影城（水悦城店）",
                "poiId":117426429,
                "price":23,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，11.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":816.6667,
                "sellPrice":"23",
                "shopId":69446044,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":0,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区正阳路157号华润万象汇第L4层L417号商铺",
                "cellShows":[

                ],
                "cityId":60,
                "dis":1609.700298032714,
                "distance":"1.6km",
                "follow":0,
                "id":26096,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.306404,
                "lng":120.41422,
                "mark":0,
                "nm":"万象影城（青岛城阳万象汇店）",
                "poiId":189013152,
                "price":39.9,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，首单1张最高立减5元",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":600,
                "sellPrice":"39.9",
                "shopId":126302594,
                "showTimes":"",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区正阳路136号",
                "cellShows":[

                ],
                "cityId":60,
                "dis":1699.9464864899935,
                "distance":"1.7km",
                "follow":0,
                "id":1115,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"4K厅",
                        "url":""
                    }
                ],
                "lat":36.304672,
                "lng":120.41496,
                "mark":0,
                "nm":"艺佳电影城",
                "poiId":1439171,
                "price":33,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，11.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"50",
                "score":622.2222,
                "sellPrice":"33",
                "shopId":4369846,
                "showTimes":"",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[
                        "4K厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"4K厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区家佳源对过利群后面青特上豪广场三楼",
                "cellShows":[

                ],
                "cityId":60,
                "dis":1928.1011233079328,
                "distance":"1.9km",
                "follow":0,
                "id":1105,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    }
                ],
                "lat":36.30759,
                "lng":120.41782,
                "mark":0,
                "nm":"国文影城（青特店）",
                "poiId":1975516,
                "price":33,
                "promotion":{
                    "cardPromotionTag":"",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"50",
                "score":541.17645,
                "sellPrice":"33",
                "shopId":5301085,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":""
                }
            },
            {
                "addr":"城阳区兴阳路702号城中城5-309",
                "cellShows":[

                ],
                "cityId":60,
                "dis":2322.850804349987,
                "distance":"2.3km",
                "follow":0,
                "id":15006,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.287525,
                "lng":120.38842,
                "mark":0,
                "nm":"金太狼4k国际影城",
                "poiId":77455443,
                "price":23,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，9.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":535.7143,
                "sellPrice":"23",
                "shopId":34169759,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区正阳中路117号青特万达广场五楼",
                "cellShows":[

                ],
                "cityId":60,
                "dis":2472.1980722524668,
                "distance":"2.5km",
                "follow":0,
                "id":27944,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.306114,
                "lng":120.42385,
                "mark":0,
                "nm":"万达影城（青岛城阳万达影城广场店）",
                "poiId":1208503311,
                "price":34.9,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，19.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":600,
                "sellPrice":"34.9",
                "shopId":1208503311,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区荟城路506号蔚蓝创新天地南区商业三层",
                "cellShows":[

                ],
                "cityId":60,
                "dis":3559.4298604052824,
                "distance":"3.6km",
                "follow":0,
                "id":27858,
                "labels":[
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"杜比全景声厅",
                        "url":""
                    }
                ],
                "lat":36.313103,
                "lng":120.43542,
                "mark":0,
                "nm":"横店电影城（青岛城阳店）",
                "poiId":696406641,
                "price":24,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，9.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":600,
                "sellPrice":"24",
                "shopId":696406641,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":0,
                    "giftTag":"",
                    "hallType":[
                        "杜比全景声厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"杜比全景声厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区棘洪滩街道青大社区中心（南万小学对面）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":6746.9787784496975,
                "distance":"6.7km",
                "follow":0,
                "id":11535,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.320045,
                "lng":120.322586,
                "mark":0,
                "nm":"棘洪滩影城",
                "poiId":5653509,
                "price":23,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，11.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":931.5789,
                "sellPrice":"23",
                "shopId":19644320,
                "showTimes":"",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区高新区世茂52+购物广场四楼万达影城",
                "cellShows":[

                ],
                "cityId":60,
                "dis":8315.629466263876,
                "distance":"8.3km",
                "follow":0,
                "id":36664,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.281456,
                "lng":120.30923,
                "mark":0,
                "nm":"万达影城（高新区世茂店）",
                "poiId":586573146,
                "price":0,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，19.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":600,
                "sellPrice":"",
                "shopId":586573146,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"城阳区黑龙江中路2111号东方城购物中心5楼",
                "cellShows":[

                ],
                "cityId":60,
                "dis":8339.927748077604,
                "distance":"8.3km",
                "follow":0,
                "id":26019,
                "labels":[
                    {
                        "color":"#F52B27",
                        "name":"安心影院",
                        "url":"http://p1.meituan.net/scarlett/946d67ef54f993a3506944cca42652af3736.png"
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"DTS:X 临境音厅",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"4K厅",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"巨幕厅",
                        "url":""
                    }
                ],
                "lat":36.23685,
                "lng":120.4279,
                "mark":0,
                "nm":"华谊兄弟影院（青岛东方城店）",
                "poiId":187928074,
                "price":39.9,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，9.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":600,
                "sellPrice":"39.9",
                "shopId":125245173,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[
                        "DTS:X 临境音厅",
                        "4K厅",
                        "巨幕厅"
                    ],
                    "hallTypeVOList":[
                        {
                            "name":"DTS:X 临境音厅",
                            "url":""
                        },
                        {
                            "name":"4K厅",
                            "url":""
                        },
                        {
                            "name":"巨幕厅",
                            "url":""
                        }
                    ],
                    "sell":1,
                    "snack":0,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"即墨区即墨市鹤山路999号家佳源购物中心三层",
                "cellShows":[

                ],
                "cityId":60,
                "dis":10250.214671006233,
                "distance":"10.3km",
                "follow":0,
                "id":7799,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.397686,
                "lng":120.41999,
                "mark":0,
                "nm":"大地影院（即墨家佳源店）",
                "poiId":4148359,
                "price":35,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，25元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":892.8572,
                "sellPrice":"35",
                "shopId":17721483,
                "showTimes":"",
                "tag":{
                    "allowRefund":0,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            },
            {
                "addr":"即墨区即墨市鹤山路939号，利群购物中心7楼（小商品城对面）",
                "cellShows":[

                ],
                "cityId":60,
                "dis":10447.566919155832,
                "distance":"10.4km",
                "follow":0,
                "id":8093,
                "labels":[
                    {
                        "color":"#6cbd03",
                        "name":"退",
                        "url":""
                    },
                    {
                        "color":"#6cbd03",
                        "name":"改签",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"小吃",
                        "url":""
                    },
                    {
                        "color":"#ff9900",
                        "name":"折扣卡",
                        "url":""
                    }
                ],
                "lat":36.398003,
                "lng":120.42765,
                "mark":0,
                "nm":"利群华艺影院（即墨激光巨幕店）",
                "poiId":4118586,
                "price":35,
                "promotion":{
                    "cardPromotionTag":"开卡特惠，24.9元起开卡",
                    "couponPromotionTag":"",
                    "merchantActivityTag":"",
                    "packShowActivityTag":"",
                    "platformActivityTag":"",
                    "starActivityTag":""
                },
                "referencePrice":"0",
                "score":878.5714,
                "sellPrice":"35",
                "shopId":17902216,
                "showTimes":"",
                "tag":{
                    "allowRefund":1,
                    "buyout":0,
                    "cityCardTag":0,
                    "deal":0,
                    "endorse":1,
                    "giftTag":"",
                    "hallType":[

                    ],
                    "hallTypeVOList":[

                    ],
                    "sell":1,
                    "snack":1,
                    "vipTag":"折扣卡"
                }
            }
        ],
        "ct_pois":[
            {
                "ct_poi":"936879945111165696_a16254_c0",
                "poiid":117426429
            },
            {
                "ct_poi":"936879945111165696_a26096_c1",
                "poiid":189013152
            },
            {
                "ct_poi":"936879945111165696_a1115_c2",
                "poiid":1439171
            },
            {
                "ct_poi":"936879945111165696_a1105_c3",
                "poiid":1975516
            },
            {
                "ct_poi":"936879945111165696_a15006_c4",
                "poiid":77455443
            },
            {
                "ct_poi":"936879945111165696_a27944_c5",
                "poiid":1208503311
            },
            {
                "ct_poi":"936879945111165696_a27858_c6",
                "poiid":696406641
            },
            {
                "ct_poi":"936879945111165696_a11535_c7",
                "poiid":5653509
            },
            {
                "ct_poi":"936879945111165696_a36664_c8",
                "poiid":586573146
            },
            {
                "ct_poi":"936879945111165696_a26019_c9",
                "poiid":187928074
            },
            {
                "ct_poi":"936879945111165696_a7799_c10",
                "poiid":4148359
            },
            {
                "ct_poi":"936879945111165696_a8093_c11",
                "poiid":4118586
            }
        ],
        "paging":{
            "hasMore":True,
            "limit":12,
            "offset":0,
            "total":92
        }
}

class CinemaHandler(BaseHandler):
    def get(self, *args, **kwargs):
        logger.info('this is in CinemaHandler')
        city_id = self.get_argument('city_id',0)
        if not city_id:
            print('in not city')
            result = {
                'cinemas':[],
                "paging":{
                    "hasMore":False,
                    "limit":12,
                    "offset":0,
                    "total":92
                }
            }
            self.JsonResponse(result)
            return
        district_id = self.get_argument('districtId',0)
        lat = self.get_argument('lat',0)
        lng = self.get_argument('lng',0)
        if lat and lng:
            distance_flag = True
        session = DBSession()
        cinema_query = session.query(Cinema).filter(Cinema.cityId==city_id)
        if int(district_id) > 0:
            cinema_query = cinema_query.filter(Cinema.districtId==district_id)
        if int(district_id) == -1:
            lat_min = float(lat) - 0.1
            lat_max = float(lat) + 0.1
            lng_min = float(lng) - 0.1
            lng_max = float(lng) + 0.1
            cinema_query = cinema_query.filter(
                        Cinema.lat>lat_min,Cinema.lat<lat_max).filter(
                        Cinema.lng>lng_min,Cinema.lng<lng_max)
        cinema_set = cinema_query.all()
        session.close()
        cinema_list = []
        for i in cinema_set:
            if distance_flag:
                distance = geodesic((lat,lng),(i.lat,i.lng))
            item = {}
            item['id'] = i.ID
            item['nm'] = i.name
            item['sellPrice'] = '22'
            item['addr'] = i.addr
            if distance_flag:
                item['distance'] = '%0.1fkm' % distance.km
            item['endorse'] = i.endorse
            item['allowRefund'] = i.allowRefund
            item['hallType'] = ''
            item['snack'] = i.snack
            item['vipDesc'] = i.vipDesc
            item['promotion'] = {'cardPromotionTag':i.cardPromotionTag}
            item['showTimes'] = i.showTimes
            cinema_list.append(item)
        result = {
            'cinemas':cinema_list,
            "paging":{
                "hasMore":True,
                "limit":12,
                "offset":0,
                "total":92
            }
        }
        self.JsonResponse(result)
