#!/usr/bin/env python
# -*- coding: UTF-8 -*-
__author__ = 'kevin'

from core.logger import logger
from core.base_controller import BaseHandler
from core.DB import DBSession
from models.city_section import CityBrand, CityDistrict, CityDistrictSub, CitySubway, CitySubwayStation

result = {
    
    "brand":{
        "name":"品牌",
        "subItems":[
            {
                "count":92,
                "id":-1,
                "name":"全部"
            },
            {
                "count":7,
                "id":188982,
                "name":"万达影城"
            },
            {
                "count":5,
                "id":204208,
                "name":"星美国际影城"
            },
            {
                "count":4,
                "id":195014,
                "name":"横店影视"
            },
            {
                "count":4,
                "id":383399,
                "name":"西海岸"
            },
            {
                "count":3,
                "id":367699,
                "name":"大商影城"
            },
            {
                "count":3,
                "id":188757,
                "name":"金逸影城"
            },
            {
                "count":3,
                "id":357245,
                "name":"CGV影城"
            },
            {
                "count":2,
                "id":494661,
                "name":"完美世界影城"
            },
            {
                "count":2,
                "id":334864,
                "name":"新世纪电影城"
            },
            {
                "count":2,
                "id":327981,
                "name":"大地影院"
            },
            {
                "count":2,
                "id":208114,
                "name":"耀莱成龙国际影城"
            },
            {
                "count":1,
                "id":495495,
                "name":"万象影城"
            },
            {
                "count":1,
                "id":484416,
                "name":"苏宁影城"
            },
            {
                "count":1,
                "id":356232,
                "name":"鲁信影城"
            },
            {
                "count":1,
                "id":192146,
                "name":"中影国际影城"
            },
            {
                "count":1,
                "id":30032,
                "name":"星美国际影城"
            },
            {
                "count":1,
                "id":201744,
                "name":"博纳国际影城"
            },
            {
                "count":1,
                "id":498523,
                "name":"红星电影世界"
            },
            {
                "count":1,
                "id":385837,
                "name":"银河欢乐影城"
            },
            {
                "count":1,
                "id":210217,
                "name":"奥斯卡国际影城"
            },
            {
                "count":1,
                "id":490925,
                "name":"东影时代影城"
            },
            {
                "count":1,
                "id":418027,
                "name":"SFC上影影城"
            },
            {
                "count":1,
                "id":324137,
                "name":"华谊兄弟"
            },
            {
                "count":1,
                "id":339563,
                "name":"泽艺影城"
            },
            {
                "count":1,
                "id":490686,
                "name":"泰禾影城"
            },
            {
                "count":1,
                "id":482488,
                "name":"星轶imax影城"
            },
            {
                "count":40,
                "id":0,
                "name":"其他"
            }
        ]
    },
    "district":{
        "name":"行政区",
        "subItems":[
            {
                "count":92,
                "id":-1,
                "name":"全部",
                "subItems":[

                ]
            },
            {
                "count":25,
                "id":137,
                "name":"黄岛区",
                "subItems":[
                    {
                        "count":25,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":8,
                        "id":46569,
                        "name":"开发区",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":9318,
                        "name":"长江路沿线",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":8900,
                        "name":"香江路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":16861,
                        "name":"胶南宏程新天地",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":14029,
                        "name":"胶南人民路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":14037,
                        "name":"双珠路/珠海路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":9121,
                        "name":"上流汇",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":23823,
                        "name":"胶南",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":16866,
                        "name":"胶南黄海学院",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":15,
                "id":133,
                "name":"市北区",
                "subItems":[
                    {
                        "count":15,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":932,
                        "name":"台东步行街",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":8418,
                        "name":"中央商务区",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":937,
                        "name":"海琴广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":6576,
                        "name":"浮山后",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":40936,
                        "name":"新都心",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":936,
                        "name":"小村庄",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":933,
                        "name":"儿童公园/青岛港",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":41283,
                        "name":"海泊桥",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":12,
                "id":3185,
                "name":"城阳区",
                "subItems":[
                    {
                        "count":12,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":43775,
                        "name":"正阳路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":9215,
                        "name":"东方城",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":9212,
                        "name":"青特上豪/家佳源",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":9211,
                        "name":"农业大学/春阳路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":9214,
                        "name":"世纪公园",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":39352,
                        "name":"动车小镇商圈",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":8,
                "id":132,
                "name":"市南区",
                "subItems":[
                    {
                        "count":8,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":4,
                        "id":929,
                        "name":"火车站/团岛",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":8412,
                        "name":"麦凯乐",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":6573,
                        "name":"云霄路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":18172,
                        "name":"万象城",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":7,
                "id":3187,
                "name":"即墨市",
                "subItems":[
                    {
                        "count":7,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":11946,
                        "name":"即墨宝龙城市广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":11945,
                        "name":"新利群商场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":18717,
                        "name":"正发利群",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":18740,
                        "name":"大润发",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":7,
                "id":135,
                "name":"李沧区",
                "subItems":[
                    {
                        "count":7,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":4,
                        "id":9453,
                        "name":"维客广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":13437,
                        "name":"万达广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":9452,
                        "name":"李沧宝龙",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":6,
                "id":3190,
                "name":"莱西市",
                "subItems":[
                    {
                        "count":6,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":43080,
                        "name":"利客来",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":45983,
                        "name":"北利群人民广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":31964,
                        "name":"姜山/莱西姜山汽车站",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":43526,
                        "name":"粮贸",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":4,
                "id":3186,
                "name":"胶州市",
                "subItems":[
                    {
                        "count":4,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":13261,
                        "name":"新城区",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":40729,
                        "name":"向阳商街",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":4,
                "id":3188,
                "name":"平度市",
                "subItems":[
                    {
                        "count":4,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":45490,
                        "name":"维客/百货大楼",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":15593,
                        "name":"维客/百货商圈",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":15595,
                        "name":"利群/尚街",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":4,
                "id":136,
                "name":"崂山区",
                "subItems":[
                    {
                        "count":4,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":940,
                        "name":"石老人海水浴场商圈",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":42890,
                        "name":"金鼎广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":8895,
                        "name":"大拇指广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":13186,
                        "name":"国信体育中心",
                        "subItems":[

                        ]
                    }
                ]
            }
        ]
    },
    "hallType":{
        "name":"特殊厅",
        "subItems":[
            {
                "count":0,
                "id":-1,
                "name":"全部"
            },
            {
                "count":0,
                "id":2,
                "name":"IMAX厅"
            },
            {
                "count":0,
                "id":3,
                "name":"CGS中国巨幕厅"
            },
            {
                "count":0,
                "id":9,
                "name":"杜比全景声厅"
            },
            {
                "count":0,
                "id":10,
                "name":"RealD厅"
            },
            {
                "count":0,
                "id":5,
                "name":"LUXE巨幕厅"
            },
            {
                "count":0,
                "id":4,
                "name":"4DX厅"
            },
            {
                "count":0,
                "id":25,
                "name":"DTS:X 临境音厅"
            },
            {
                "count":0,
                "id":24,
                "name":"儿童厅"
            },
            {
                "count":0,
                "id":8,
                "name":"4K厅"
            },
            {
                "count":0,
                "id":7,
                "name":"4D厅"
            },
            {
                "count":0,
                "id":14,
                "name":"60帧厅"
            },
            {
                "count":0,
                "id":16,
                "name":"120帧/4K厅"
            },
            {
                "count":0,
                "id":6,
                "name":"巨幕厅"
            },
            {
                "count":0,
                "id":29,
                "name":"MX4D厅"
            }
        ]
    },
    "service":{
        "name":"服务",
        "subItems":[
            {
                "count":92,
                "id":-1,
                "name":"全部"
            },
            {
                "count":71,
                "id":3,
                "name":"可改签"
            },
            {
                "count":35,
                "id":2,
                "name":"可退票"
            }
        ]
    },
    "showType":None,
    "subway":{
        "name":"地铁",
        "subItems":[
            {
                "count":92,
                "id":-1,
                "name":"全部",
                "subItems":[

                ]
            },
            {
                "count":28,
                "id":188,
                "name":"2号线",
                "subItems":[
                    {
                        "count":28,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":4,
                        "id":4985,
                        "name":"李村",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":5895,
                        "name":"台东",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":4983,
                        "name":"五四广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":4973,
                        "name":"李村公园",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":5893,
                        "name":"利津路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4981,
                        "name":"苗岭路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4986,
                        "name":"燕儿岛路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4988,
                        "name":"浮山所",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4975,
                        "name":"石老人浴场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":5894,
                        "name":"泰山路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":4984,
                        "name":"高雄路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":4987,
                        "name":"芝泉路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":4971,
                        "name":"辽阳东路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":4972,
                        "name":"同安路",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":27,
                "id":133,
                "name":"3号线",
                "subItems":[
                    {
                        "count":27,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":4,
                        "id":4293,
                        "name":"敦化路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":4,
                        "id":3787,
                        "name":"李村",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":4294,
                        "name":"错埠岭",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":4290,
                        "name":"五四广场",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":3789,
                        "name":"双山",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4299,
                        "name":"青岛站",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4295,
                        "name":"江西路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":4289,
                        "name":"清江路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":4297,
                        "name":"延安三路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":3785,
                        "name":"万年泉路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":3788,
                        "name":"长沙路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":3791,
                        "name":"君峰路",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":2,
                "id":189,
                "name":"11号线",
                "subItems":[
                    {
                        "count":2,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":2,
                        "id":5008,
                        "name":"苗岭路",
                        "subItems":[

                        ]
                    }
                ]
            },
            {
                "count":9,
                "id":190,
                "name":"13号线",
                "subItems":[
                    {
                        "count":9,
                        "id":-1,
                        "name":"全部",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":5020,
                        "name":"井冈山路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":3,
                        "id":5013,
                        "name":"积米崖",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":5018,
                        "name":"朝阳山",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":5031,
                        "name":"凤凰山路",
                        "subItems":[

                        ]
                    },
                    {
                        "count":1,
                        "id":5025,
                        "name":"双珠路",
                        "subItems":[

                        ]
                    }
                ]
            }
        ]
    },
    "timeRanges":{
        "name":"时段",
        "subItems":[
            {
                "count":0,
                "id":100000000,
                "name":"不限时段"
            },
            {
                "count":0,
                "id":100000900,
                "name":"9点以前"
            },
            {
                "count":0,
                "id":109001100,
                "name":"9-11点"
            },
            {
                "count":0,
                "id":111001300,
                "name":"11-13点"
            },
            {
                "count":0,
                "id":113001500,
                "name":"13-15点"
            },
            {
                "count":0,
                "id":115001700,
                "name":"15-17点"
            },
            {
                "count":0,
                "id":117001900,
                "name":"17-19点"
            },
            {
                "count":0,
                "id":119002100,
                "name":"19-21点"
            },
            {
                "count":0,
                "id":121002300,
                "name":"21-23点"
            },
            {
                "count":0,
                "id":123002359,
                "name":"23点以后"
            }
        ]
    }
}


result2 = {
    
    "brand":{
        "name":"品牌",
        "subItems":[]
    },
    "district":{
        "name":"行政区",
        "subItems":[]
    },
    "hallType":{
        "name":"特殊厅",
        "subItems":[
            {
                "count":0,
                "id":-1,
                "name":"全部"
            },
            {
                "count":0,
                "id":2,
                "name":"IMAX厅"
            },
            {
                "count":0,
                "id":3,
                "name":"CGS中国巨幕厅"
            },
            {
                "count":0,
                "id":9,
                "name":"杜比全景声厅"
            },
            {
                "count":0,
                "id":10,
                "name":"RealD厅"
            },
            {
                "count":0,
                "id":5,
                "name":"LUXE巨幕厅"
            },
            {
                "count":0,
                "id":4,
                "name":"4DX厅"
            },
            {
                "count":0,
                "id":25,
                "name":"DTS:X 临境音厅"
            },
            {
                "count":0,
                "id":24,
                "name":"儿童厅"
            },
            {
                "count":0,
                "id":8,
                "name":"4K厅"
            },
            {
                "count":0,
                "id":7,
                "name":"4D厅"
            },
            {
                "count":0,
                "id":14,
                "name":"60帧厅"
            },
            {
                "count":0,
                "id":16,
                "name":"120帧/4K厅"
            },
            {
                "count":0,
                "id":6,
                "name":"巨幕厅"
            },
            {
                "count":0,
                "id":29,
                "name":"MX4D厅"
            }
        ]
    },
    "service":{
        "name":"服务",
        "subItems":[
            {
                "count":92,
                "id":-1,
                "name":"全部"
            },
            {
                "count":71,
                "id":3,
                "name":"可改签"
            },
            {
                "count":35,
                "id":2,
                "name":"可退票"
            }
        ]
    },
    "showType":None,
    "subway":{
        "name":"地铁",
        "subItems":[]
    },
    "timeRanges":{
        "name":"时段",
        "subItems":[
            {
                "count":0,
                "id":100000000,
                "name":"不限时段"
            },
            {
                "count":0,
                "id":100000900,
                "name":"9点以前"
            },
            {
                "count":0,
                "id":109001100,
                "name":"9-11点"
            },
            {
                "count":0,
                "id":111001300,
                "name":"11-13点"
            },
            {
                "count":0,
                "id":113001500,
                "name":"13-15点"
            },
            {
                "count":0,
                "id":115001700,
                "name":"15-17点"
            },
            {
                "count":0,
                "id":117001900,
                "name":"17-19点"
            },
            {
                "count":0,
                "id":119002100,
                "name":"19-21点"
            },
            {
                "count":0,
                "id":121002300,
                "name":"21-23点"
            },
            {
                "count":0,
                "id":123002359,
                "name":"23点以后"
            }
        ]
    }
}
class FilterCinemasHandler(BaseHandler):
    def get(self, *args, **kwargs):
        city_id = self.get_argument('city_id',60)
        logger.info('this is in FilterCinemasHandler:%s' % city_id)
        session = DBSession()
        cb_set = session.query(CityBrand).filter(CityBrand.CityId==city_id).all()
        cb_subItems = [{
                "count":92,
                "id":-1,
                "name":"全部"
            }]
        for i in cb_set:
            cb_subItems.append({
                    "count":i.Count,
                    "id":i.ID,
                    "name":i.Name
                })
        result2['brand']["subItems"] = cb_subItems
        cd_set = session.query(CityDistrict).filter(CityDistrict.CityId==city_id).all()
        cd_subItems = [{
                    "count":92,
                    "id":-1,
                    "name":"全部",
                    "subItems":[]
            }]
        for i in cd_set:
            district_id = i.ID
            cs_list = [{"count":25,
                        "id":-1,
                        "name":"全部",
                        "subItems":[]
                        }]
            cds_set = session.query(CityDistrictSub).filter(CityDistrictSub.DistrictId==district_id).all()
            for j in cds_set:
                cs_list.append({
                    "count":j.Count,
                    "id":j.ID,
                    "name":j.Name,
                    "subItems":[]
                    })
            cd_subItems.append({
                "count":i.Count,
                "id":i.ID,
                "name":i.Name,
                "subItems":cs_list
            })
        result2['district']["subItems"] = cd_subItems
        cs_set = session.query(CitySubway).filter(CitySubway.CityId==city_id).all()
        cs_subItems = [{
                    "count":92,
                    "id":-1,
                    "name":"全部",
                    "subItems":[]
            }]
        for i in cs_set:
            cs_id = i.ID
            css_list = [{
                "count":25,
                "id":-1,
                "name":"全部",
                "subItems":[]
            }]
            css_set = session.query(CitySubwayStation).filter(CitySubwayStation.SubwayId==cs_id).all()
            for j in css_set:
                css_list.append({
                    "count":j.Count,
                    "id":j.ID,
                    "name":j.Name,
                    "subItems":[]
                })
            cs_subItems.append({
                "count":i.Count,
                "id":i.ID,
                "name":i.Name,
                "subItems":css_list
            })
        result2['subway']["subItems"] = cs_subItems
        session.close()
        logger.info('this is in IndexHandler')
        self.JsonResponse(result2)